// auto generated by build/layouts.js

   module.exports = {
      get
   };

   function get() {
      return `<section class="todoapp app-layout">
  <header class="header">
    <h1>todos</h1>
  </header>
  <!-- This section should be hidden by default and shown when there are todos -->
  <section class="main">

  </section>
  <!-- This footer should be hidden by default and shown when there are todos -->
  <footer class="footer">

  </footer>
</section>
<footer class="info">
  <p>Double-click to edit a todo</p>
  <p>Template by <a href="http://sindresorhus.com">Sindre Sorhus</a></p>
  <p>Created by <a href="http://todomvc.com">you</a></p>
  <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>
`;
   }