// auto generated by build/layouts.js

module.exports = {
   get: get
};

const layouts = {
   'app-layout': require('./app-layout/app-layout.html.js')
};

function get(type) {
   if (layouts[type] == null) {
      console.log('layout not found for ', type);
   }

   return layouts[type].get();
}